config/routes.rb
Rails.application.routes.draw do
  

  
  resources :samples

  resources :submarkets

  resources :markets

  resources :brands

  resources :referencestyles

  resources :productcategories

  resources :seasons

  resources :trackingsheetdocuments

  resources :trackingsheetimages

  resources :costsheets

  resources :testings

  resources :hardwares

  resources :components

  resources :divisions 

  resources :trackingsheets
	
	resources :processmasters

  resources :proces, :path => "process" #Url Aliasing from proces ->  process
  
   resources :styles

  resources :usertypes

  resources :users

  devise_for :users, :skip => [:registrations, :sessions]
	as :trackingsheetdocument do
			get "deletetsdoc"=> "trackingsheetdocuments#deletetsdoc", :as => :deletetsdoc
      
	end
  
	as :trackingsheetimage do
			get "deletetsimg"=> "trackingsheetimages#deletetsimg", :as => :deletetsimg
      
	end
  
  
  
	as :trackingsheet do
			get "get_history"=> "trackingsheets#get_history", :as => :get_history
      get "get_comments"=> "trackingsheets#get_comments", :as => :get_comments
			get "lockme"=> "trackingsheets#lockme", :as => :lockme
			get "tocsv"=> "trackingsheets#tocsv", :as => :tocsv
	end
	as :costsheet do
			get "ajaxcreate_costsheets"=> "costsheets#ajaxcreate_costsheets", :as => :ajaxcreate_costsheets
      get "deletetscst"=> "costsheets#deletetscst", :as => :deletetscst
     
	end
	as :testing do
			get "ajaxcreate_testings"=> "testings#ajaxcreate_testings", :as => :ajaxcreate_testings
      get "deletetstst"=> "testings#deletetstst", :as => :deletetstst
     
	end
	as :hardware do
			get "ajaxcreate_hardwares"=> "hardwares#ajaxcreate_hardwares", :as => :ajaxcreate_hardwares
      get "deletetshrd"=> "hardwares#deletetshrd", :as => :deletetshrd
      
     
	end
	as :component do
			get "ajaxcreate_components"=> "components#ajaxcreate_components", :as => :ajaxcreate_components
      get "deletetscmp"=> "components#deletetscmp", :as => :deletetscmp
     
	end
	as :sample do
			get "ajaxcreate_samples"=> "samples#ajaxcreate_samples", :as => :ajaxcreate_samples
      get "deletetssmp"=> "samples#deletetssmp", :as => :deletetssmp
     
	end
	as :style do
			get "get_styles"=> "styles#get_styles", :as => :get_styles
	end
	as :season do
			get "ajaxcreate_seasons"=> "seasons#ajaxcreate_seasons", :as => :ajaxcreate_seasons
     
	end
	as :productcategory do
			get "ajaxcreate_productcategories"=> "productcategories#ajaxcreate_productcategories", :as => :ajaxcreate_productcategories
     
	end
	as :referencestyle do
			get "ajaxcreate_referencestyles"=> "referencestyles#ajaxcreate_referencestyles", :as => :ajaxcreate_referencestyles
     
	end
	as :brand do
			get "ajaxcreate_brands"=> "brands#ajaxcreate_brands", :as => :ajaxcreate_brands
     
	end
	as :market do
			get "ajaxcreate_markets"=> "markets#ajaxcreate_markets", :as => :ajaxcreate_markets
     
	end
	as :submarket do
			get "ajaxcreate_submarkets"=> "submarkets#ajaxcreate_submarkets", :as => :ajaxcreate_submarkets
     
	end
  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
		get "custom_search"=> "users#custom_search", :as => :custom_search
		get "get_users"=> "users#get_users", :as => :get_users
		#get "/:id/edit" => "users#edit", :as => :edit_user_path
		#delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
	root :to => 'home#index'
end

app/models/submarket.rb
class Submarket
  include Mongoid::Document
	include Mongoid::Timestamps

  field :name, type: String

	has_many :processmasters
end

app/controllers/submarkets_controller.rb
class SubmarketsController < ApplicationController
  before_action :set_submarket, only: [:show, :edit, :update, :destroy]
	layout 'vendor_portal'
  # GET /submarkets
  # GET /submarkets.json
  def index
    @submarkets = Submarket.all
  end

  # GET /submarkets/1
  # GET /submarkets/1.json
  def show
  end

  # GET /submarkets/new
  def new
    @submarket = Submarket.new
  end

  # GET /submarkets/1/edit
  def edit
  end

  # POST /submarkets
  # POST /submarkets.json
  def create
    @submarket = Submarket.new(submarket_params)

    respond_to do |format|
      if @submarket.save
        format.html { redirect_to submarkets_url, notice: 'Submarket was successfully created.' }
        format.json { render :show, status: :created, location: @submarket }
      else
        format.html { render :new }
        format.json { render json: @submarket.errors, status: :unprocessable_entity }
      end
    end
  end
		
	def ajaxcreate_submarkets
    @submarket = Submarket.new(:name=>params[:field])
		if @submarket.save
        @submarkets = Submarket.all
   		  render json: Hash[@submarkets.map { |v| [ v[:id].to_s, v[:name].to_s ] } ]
      end
   
  end

  # PATCH/PUT /submarkets/1
  # PATCH/PUT /submarkets/1.json
  def update
    respond_to do |format|
      if @submarket.update(submarket_params)
        format.html { redirect_to submarkets_url, notice: 'Submarket was successfully updated.' }
        format.json { render :show, status: :ok, location: @submarket }
      else
        format.html { render :edit }
        format.json { render json: @submarket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submarkets/1
  # DELETE /submarkets/1.json
  def destroy
    @submarket.destroy
    respond_to do |format|
      format.html { redirect_to submarkets_url, notice: 'Submarket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submarket
      @submarket = Submarket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submarket_params
      params.require(:submarket).permit(:name)
    end
end

app/helpers/submarkets_helper.rb
module SubmarketsHelper
end

app/views/submarkets/_form.html.erb
<%= form_for @submarket, :html => {:class => "form-horizontal"} do |f| %>
	 <% if @submarket.errors.any? %>
		 <div id="error_explanation">
		   <h2><%= pluralize(@submarket.errors.count, "error") %> prohibited this post from being saved:</h2>

		   <ul>
		   <% @submarket.errors.full_messages.each do |message| %>
		     <li><%= message %></li>
		   <% end %>
		   </ul>
		 </div>
	 <% end %>
<div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
	<div class="widget-box">
		<div class="control-group">
		<label class="control-label">Name</label>
			<div class="controls">
					<%= f.text_field :name, class:"span6",placeholder:"Submarket Name" %>
			</div>
		</div>
		
	<div class="form-actions">
		<%= f.submit 'Save', :class => 'btn btn-success btn-xs' %>
	</div>  
</div>

</div>
</div>


<% end %>

app/views/submarkets/edit.html.erb
<%= render 'form' %>

app/views/submarkets/index.html.erb
<div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <div class="widget-box">
          <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
              <thead>
                <tr>
                  <th>Sl</th>
                  <th>Sub Market Name</th>
                  <th>Created Date</th>
                  <th colspan='2'>Actions</th>
                </tr>
              </thead>
              <tbody>
								<% @i=1 %>
								<% @submarkets.each do |submarket| %>
									<tr class="gradeX">
										<td><%= @i %></td>
										<td><%= submarket.name %></td>
										<td><%= submarket.created_at.strftime("%d %b %Y,%T") %></td>
										<td><div style="text-align:center;"><%= link_to 'Edit', edit_submarket_path(submarket),class:'btn btn-warning' %></div></td>
										<td><div style="text-align:center;"><%= link_to 'Delete', submarket, method: :delete, data: { header:"Sub Market",confirm:(submarket.name)+' ?'},class:'btn btn-danger' %></div></td>
									</tr>
									<% @i+=1%>
								<% end %>	
							</tbody>
            </table>
				
         	</div>
       </div>
   </div>
			<%= link_to 'New Sub Market', new_submarket_path ,class:'btn btn-success' %>
</div>

app/views/submarkets/new.html.erb
<%= render 'form' %>

app/views/submarkets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @submarket.name %>
</p>

<%= link_to 'Edit', edit_submarket_path(@submarket) %> |
<%= link_to 'Back', submarkets_path %>