config/routes.rb
Rails.application.routes.draw do
  

  
  resources :samples

  resources :submarkets

  resources :markets

  resources :brands

  resources :referencestyles

  resources :productcategories

  resources :seasons

  resources :trackingsheetdocuments

  resources :trackingsheetimages

  resources :costsheets

  resources :testings

  resources :hardwares

  resources :components

  resources :divisions 

  resources :trackingsheets
	
	resources :processmasters

  resources :proces, :path => "process" #Url Aliasing from proces ->  process
  
   resources :styles

  resources :usertypes

  resources :users

  devise_for :users, :skip => [:registrations, :sessions]
	as :trackingsheetdocument do
			get "deletetsdoc"=> "trackingsheetdocuments#deletetsdoc", :as => :deletetsdoc
      
	end
  
	as :trackingsheetimage do
			get "deletetsimg"=> "trackingsheetimages#deletetsimg", :as => :deletetsimg
      
	end
  
  
  
	as :trackingsheet do
			get "get_history"=> "trackingsheets#get_history", :as => :get_history
      get "get_comments"=> "trackingsheets#get_comments", :as => :get_comments
			get "lockme"=> "trackingsheets#lockme", :as => :lockme
			get "tocsv"=> "trackingsheets#tocsv", :as => :tocsv
	end
	as :costsheet do
			get "ajaxcreate_costsheets"=> "costsheets#ajaxcreate_costsheets", :as => :ajaxcreate_costsheets
      get "deletetscst"=> "costsheets#deletetscst", :as => :deletetscst
     
	end
	as :testing do
			get "ajaxcreate_testings"=> "testings#ajaxcreate_testings", :as => :ajaxcreate_testings
      get "deletetstst"=> "testings#deletetstst", :as => :deletetstst
     
	end
	as :hardware do
			get "ajaxcreate_hardwares"=> "hardwares#ajaxcreate_hardwares", :as => :ajaxcreate_hardwares
      get "deletetshrd"=> "hardwares#deletetshrd", :as => :deletetshrd
      
     
	end
	as :component do
			get "ajaxcreate_components"=> "components#ajaxcreate_components", :as => :ajaxcreate_components
      get "deletetscmp"=> "components#deletetscmp", :as => :deletetscmp
     
	end
	as :sample do
			get "ajaxcreate_samples"=> "samples#ajaxcreate_samples", :as => :ajaxcreate_samples
      get "deletetssmp"=> "samples#deletetssmp", :as => :deletetssmp
     
	end
	as :style do
			get "get_styles"=> "styles#get_styles", :as => :get_styles
	end
	as :season do
			get "ajaxcreate_seasons"=> "seasons#ajaxcreate_seasons", :as => :ajaxcreate_seasons
     
	end
	as :productcategory do
			get "ajaxcreate_productcategories"=> "productcategories#ajaxcreate_productcategories", :as => :ajaxcreate_productcategories
     
	end
	as :referencestyle do
			get "ajaxcreate_referencestyles"=> "referencestyles#ajaxcreate_referencestyles", :as => :ajaxcreate_referencestyles
     
	end
	as :brand do
			get "ajaxcreate_brands"=> "brands#ajaxcreate_brands", :as => :ajaxcreate_brands
     
	end
	as :market do
			get "ajaxcreate_markets"=> "markets#ajaxcreate_markets", :as => :ajaxcreate_markets
     
	end
	as :submarket do
			get "ajaxcreate_submarkets"=> "submarkets#ajaxcreate_submarkets", :as => :ajaxcreate_submarkets
     
	end
  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
		get "custom_search"=> "users#custom_search", :as => :custom_search
		get "get_users"=> "users#get_users", :as => :get_users
		#get "/:id/edit" => "users#edit", :as => :edit_user_path
		#delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
	root :to => 'home#index'
end

app/models/trackingsheetdocument.rb
class Trackingsheetdocument
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps

  field :description, type: String
	field :trackingsheet, type: String
	field :procesmaster, type: String

	belongs_to :trackingsheet
	belongs_to :processmaster
	belongs_to :user

	has_mongoid_attached_file :document,
      :url => "/system/attachments/:id/:basename.:extension", 
          
      :path => ":rails_root/public/system/attachments/:id/:basename.:extension"
      
  do_not_validate_attachment_file_type :document, :content_type => [ 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ]
end

app/controllers/trackingsheetdocuments_controller.rb
class TrackingsheetdocumentsController < ApplicationController
  before_action :set_trackingsheetdocument, only: [:show, :edit, :update, :destroy]
	layout 'vendor_portal_null'

	#for authentication
	before_filter :authenticate_user!

  # GET /trackingsheetdocuments
  # GET /trackingsheetdocuments.json
  def index
    @trackingsheetdocuments = Trackingsheetdocument.all('trackingsheet_id'=>params[:trackingsheetid]) 
	  @trackingsheetdocument = Trackingsheetdocument.new
  end

  # GET /trackingsheetdocuments/1
  # GET /trackingsheetdocuments/1.json
  def show
  end

  # GET /trackingsheetdocuments/new
  def new
    @trackingsheetdocument = Trackingsheetdocument.new
  end

  # GET /trackingsheetdocuments/1/edit
  def edit
  end

  # POST /trackingsheetdocuments
  # POST /trackingsheetdocuments.json
  def create
    @trackingsheetdocument = Trackingsheetdocument.new(trackingsheetdocument_params)

    respond_to do |format|
      if @trackingsheetdocument.save
       # format.html { redirect_to @trackingsheetdocument, notice: 'Trackingsheetdocument was successfully created.' }
        #format.json { render :show, status: :created, location: @trackingsheetdocument }
        ###### new starts
        @trackingsheetlog=Trackingsheetlog.where('trackingsheet_id'=>trackingsheetdocument_params[:trackingsheet],"sessionid"=>session[:session_id],"tabname"=>VendorPortal::Application.config.documents) 
   
   
     if @trackingsheetlog.count== 0
       @trackingsheetlog = Trackingsheetlog.new("trackingsheet_id"=>trackingsheetdocument_params[:trackingsheet],"useremail"=>current_user.email,"sessionid"=>session[:session_id],"tabname"=>VendorPortal::Application.config.documents)
      @trackingsheetlog.save
    else
     @trackingsheetlog.each do |tslog|
     @trackingsheetlogobj=Trackingsheetlog.find(tslog.id)
     @trackingsheetlogobj.update_attributes(:trackingsheet_id=>trackingsheetdocument_params[:trackingsheet],:useremail=>current_user.email,:sessionid=>session[:session_id],:updated_at=>DateTime.now,:tabname=>VendorPortal::Application.config.documents)
    break
       end    
      
     end     
    
        ##### new ends
      else
        #format.html { render :new }
       # format.json { render json: @trackingsheetdocument.errors, status: :unprocessable_entity }
      end
      render :text=>true
      return false
    end
    
  end

  # PATCH/PUT /trackingsheetdocuments/1
  # PATCH/PUT /trackingsheetdocuments/1.json
  def update
    respond_to do |format|
      if @trackingsheetdocument.update(trackingsheetdocument_params)
        #format.html { redirect_to @trackingsheetdocument, notice: 'Trackingsheetdocument was successfully updated.' }
        #format.json { render :show, status: :ok, location: @trackingsheetdocument }
        ###### new starts
        @trackingsheetlog=Trackingsheetlog.where('trackingsheet_id'=>@trackingsheetdocument.trackingsheet.id,"sessionid"=>session[:session_id],"tabname"=>VendorPortal::Application.config.documents) 
   
   
     if @trackingsheetlog.count== 0
       @trackingsheetlog = Trackingsheetlog.new("trackingsheet_id"=>@trackingsheetdocument.trackingsheet.id,"useremail"=>current_user.email,"sessionid"=>session[:session_id],"tabname"=>VendorPortal::Application.config.documents)
      @trackingsheetlog.save
    else
     @trackingsheetlog.each do |tslog|
     @trackingsheetlogobj=Trackingsheetlog.find(tslog.id)
     @trackingsheetlogobj.update_attributes(:trackingsheet_id=>@trackingsheetdocument.trackingsheet.id,:useremail=>current_user.email,:sessionid=>session[:session_id],:updated_at=>DateTime.now,:tabname=>VendorPortal::Application.config.documents)
    break
       end    
      
     end     
    
        ##### new ends 
      else
        #format.html { render :edit }
        #format.json { render json: @trackingsheetdocument.errors, status: :unprocessable_entity }
      end
      render :text=>true
      return false
    end
    
      
  end

  # DELETE /trackingsheetdocuments/1
  # DELETE /trackingsheetdocuments/1.json
  def destroy
    @processmaster_id=@trackingsheetdocument.trackingsheet.processmaster.id
    @trackingsheetdocument.destroy
   respond_to do |format|
      format.html { redirect_to trackingsheets_url+"?processmaster_id="+@processmaster_id, notice: 'Document was successfully deleted.' }
      #format.html { redirect_to trackingsheetdocuments_url, notice: 'Trackingsheetdocument was successfully destroyed.' }
      format.json { head :no_content }
   end
  end
  
  def deletetsdoc
    @trackingsheetdocument = Trackingsheetdocument.find(params[:tsdocid])
    @tsid=@trackingsheetdocument.trackingsheet.id
    @trackingsheetdocument.destroy
    ###### new starts
    @trackingsheetlog=Trackingsheetlog.where('trackingsheet_id'=> @tsid,"sessionid"=>session[:session_id],"tabname"=>VendorPortal::Application.config.documents) 
   
   
 if @trackingsheetlog.count== 0
   @trackingsheetlog = Trackingsheetlog.new("trackingsheet_id"=> @tsid,"useremail"=>current_user.email,"sessionid"=>session[:session_id],"tabname"=>VendorPortal::Application.config.documents)
  @trackingsheetlog.save
else
 @trackingsheetlog.each do |tslog|
 @trackingsheetlogobj=Trackingsheetlog.find(tslog.id)
 @trackingsheetlogobj.update_attributes(:trackingsheet_id=> @tsid,:useremail=>current_user.email,:sessionid=>session[:session_id],:updated_at=>DateTime.now,:tabname=>VendorPortal::Application.config.documents)
break
   end    
      
 end     
    
    ##### new ends  
    render :text=>true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trackingsheetdocument
      @trackingsheetdocument = Trackingsheetdocument.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trackingsheetdocument_params
      params.require(:trackingsheetdocument).permit(:document, :description,:trackingsheet,:processmaster).merge(:user=>current_user)
    end
end

app/helpers/trackingsheetdocuments_helper.rb
module TrackingsheetdocumentsHelper
end

app/views/trackingsheetdocuments/_form.html.erb
<%= simple_form_for(@trackingsheetdocument) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :document %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trackingsheetdocuments/edit.html.erb
<h1>Editing Trackingsheetdocument</h1>

<%= render 'form' %>

<%= link_to 'Show', @trackingsheetdocument %> |
<%= link_to 'Back', trackingsheetdocuments_path %>

app/views/trackingsheetdocuments/index.html.erb
<%= form_for @trackingsheetdocument,  :html => {:target=>"upload_frame", :multipart => true,:class => "form-horizontal" } do |f| %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="widget-box">
			<div class="widget-content nopadding">
				<table class="table table-bordered data-table with-check">
					<tbody>
						<tr>
							<td class="span3" style="text-align:center;">
								
									Description
									
							</td>
							<td class="span4" style="text-align:center;">
								
										<%= f.text_field :description, class:"span12",placeholder:"description" %>
										<%= hidden_field(:trackingsheetdocument, :trackingsheet, :value =>params[:trackingsheetid]) %>
										<%= hidden_field(:trackingsheetdocument, :processmaster, :value =>params[:processmasterid]) %>
							</td>
							<td class="span3" style="text-align:center;">
								
								Document
									
							</td>
							<td class="span4" style="text-align:center;">
								
										<%= f.file_field :document,class:'trackingsheetdocument' %>
									
							</td>
							<td class="span4" style="text-align:center;">
										<%=link_to 'Upload','#',:class=>'add-doc btn btn-success btn-xs'  %>
									<div class='hide-me'>	<%= f.submit 'Upload', :class => 'submit-ts-doc btn btn-success btn-xs' %></div>
							</td>	
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

 <% end %>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-file"></i>
				</span>
				<h5>Listing Trackingsheet Documents</h5>
				</div>
			<div class="widget-content nopadding">
				<table>
					
					<tbody>
						<tr>
								<td  colspan="4" style="border:none;">
									<table style="border:none;width:100%;">
										<thead>
											<th style="border:none;width:20%;border-right: 1px solid #333 !important;text-align:center;">Description
											</th>
											<th style="border:none;width:40%;border-right: 1px solid #333 !important;text-align:center;">File
											</th>
											
											<th style="border:none;width:10%;border-right: 1px solid #333 !important;text-align:center;">View file
											</th>
											
											<th  style="border:none;width:10%;border-right: 1px solid #333 !important;text-align:center;">Added By
											</th>
											<th  style="border:none;width:10%;border-right: 1px solid #333 !important;text-align:center;">Action
											</th>
										</thead>
									</table>
								</td>
							</tr>
						<% @trackingsheetdocuments.each do |trackingsheetdocument| %>
							<tr>
							<td  colspan="4" style="border:none;">
							<%= form_for trackingsheetdocument,  :html => {:target=>"upload_frame",:multipart => true,:class => "form-horizontal" } do |f| %>
							
							
<!-- newly added for modal starts-->
<div class="modal fade myclosemodal" id="delete-confirm">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Are you sure you want to delete this document?</h3>
  </div>
 
  <div class="delete-modal-footer">
	
    
   
  </div>
</div>
<!-- newly added for modal ends-->		
							
							<table style="border:none;">
								<tr style="border-top: 1px solid #333 !important;">
									<td style= "width:22.1%;text-align: center;border-right: 1px solid #333 !important;">
										<%= f.text_field :description, class:"span10",placeholder:"description" %>
										<%= hidden_field(:trackingsheetdocument, :trackingsheet,:value =>trackingsheetdocument.trackingsheet.id) %>
										<%= hidden_field(:trackingsheetdocument, :processmaster, :value =>trackingsheetdocument.processmaster.id) %>
									</td>
									<td style= "width:44.7%; text-align: left;border-right: 1px solid #333 !important;">
										<%= link_to trackingsheetdocument.document_file_name,trackingsheetdocument.document.url.to_s  %>
										<%= f.file_field :document,class:'trackingsheetdocument' %>
									</td>
									<td width="10%" style="text-align:center;border-right: 1px solid #333 !important;">
									<div><%= link_to 'View', trackingsheetdocument.document.url, :class => 'btn btn-info btn-xs', :style => "width:70px;" %>
		<a href="#delete-confirm" data-id="<%= trackingsheetdocument.id %>" class="delete-confirm btn btn-danger" style="width:70px;">Delete</a>						
									</div>
								</td>
									<td style= "width:11.1%;text-align:center;border-right: 1px solid #333 !important;">
										
										<div><%= trackingsheetdocument.user.try(:firstname)+' '+trackingsheetdocument.user.try(:lastname).to_s %></div>
									</td>
									<td style= "width:11.2%;text-align:center;">
										
													<%=link_to 'Update','#',:class=>'add-doc btn btn-success btn-xs', :style =>"width:70px;"  %>
									<div class='hide-me'>	<%= f.submit 'Update', :class => 'submit-ts-doc btn btn-success btn-xs' %></div>
																			
									</td>	
									<!--<td><%#= link_to 'Destroy', trackingsheetdocument, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
								</tr>
								</table>
								</td>
								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>
<iframe id="upload_frame" name="upload_frame" style="display: none" loaded='true'></iframe>
<script type="text/javascripts">

$('.add-doc').on('click',function(){
$('#upload_frame').attr('loaded','false');
$(this).next().find('.submit-ts-doc').trigger('click');
});

$('#upload_frame').load(function(){
if($(this).attr('loaded')!='true'){

getdocuments();

$('#upload_frame').attr('loaded','true');
}
});


//newly added
$('#delete-confirm').on('show', function() {
  var $submit = $(this).find('.btn-danger'),
      href = $submit.attr('href');
  $submit.attr('href', href.replace('pony', $(this).data('id')));
});

//delete prompt 
 $('.delete-confirm').on('click',function(e) {
 //alert("you clicked");
  e.preventDefault();
  var content='<a href="#"  class="btn btn-danger delete-confirmed" document_id='+$(this).attr('data-id')+'>Delete</a> <a href="#"  class="btn btn-info btnclose">Cancel</a>';
  $('.delete-modal-footer').html(content);
  deleteinit();
  $('#delete-confirm').data('id', $(this).data('id')).modal('show');
});

function deleteinit(){
	$('.delete-confirmed').on('click',function(e) {
		var me=$(this);
		$.get('/deletetsdoc',{
			tsdocid:me.attr('document_id')
		},function(){
			getdocuments();
		});
	
	});
   //for cancel button in delete modal
    $('.btnclose').on('click',function(e) {
   	 $(".myclosemodal").modal("hide");
    });
	
}


 function getdocuments(){
	 $.get("/trackingsheetdocuments", {
	     trackingsheetid:$('#trackingsheetdocument_trackingsheet').val(),
	 		processmasterid:$('#trackingsheetdocument_processmaster').val()
	   },function(data){
	   		$('.modal').css('width','80%');
	   		$('.modal').css('left','10%');
	   		$('.modal').css('top','13%');
	 		$('.modal-body').html('');
	 		$('.modal-body').html(data);
		
	 });
}
</script>

app/views/trackingsheetdocuments/new.html.erb
<h1>New Trackingsheetdocument</h1>

<%= render 'form' %>

<%= link_to 'Back', trackingsheetdocuments_path %>

app/views/trackingsheetdocuments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document:</strong>
  <%= @trackingsheetdocument.document %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trackingsheetdocument.description %>
</p>

<%= link_to 'Edit', edit_trackingsheetdocument_path(@trackingsheetdocument) %> |
<%= link_to 'Back', trackingsheetdocuments_path %>